const FLAG_MESSAGES: Record<string, string> = {
  "PHY.TEMPERATURE_LIMIT_EXCEEDED": "Design temperature exceeds managed material limit.",
  "PHY.THICKNESS_BELOW_MINIMUM": "Current wall thickness is below required minimum thickness.",
  "PHY.REMAINING_LIFE_CRITICAL": "Remaining life is critically low.",
  "STD.HYDROTEST_CHLORIDE_LIMIT_EXCEEDED": "Hydrotest chloride exceeds material limit.",
  "PHY.CORROSION_RATE_UNREALISTIC": "Calculated corrosion rate is outside realistic engineering bounds.",
  "PHY.VESSEL_THICKNESS_BELOW_REQUIRED": "Vessel shell thickness is below required value.",
  "PHY.VESSEL_EXTERNAL_PRESSURE_RISK": "External pressure utilization exceeds conservative threshold.",
  "PHY.VESSEL_NOZZLE_REINFORCEMENT_RISK": "Nozzle reinforcement screen indicates insufficient area.",
  "PHY.ROTATING_VIBRATION_CRITICAL": "Vibration exceeds critical threshold for selected machine.",
  "PHY.ROTATING_VIBRATION_ABOVE_LIMIT": "Vibration exceeds adjusted alert limit for machine/driver/criticality.",
  "PHY.ROTATING_NOZZLE_LOAD_EXCEEDED": "Applied nozzle load exceeds allowed ratio.",
  "PHY.ROTATING_NOZZLE_LOAD_NEAR_LIMIT": "Nozzle load is above conservative warning limit.",
  "PHY.ROTATING_SPEED_CRITICAL_OUT_OF_SCOPE": "Running speed is critically outside screened operating envelope.",
  "STD.ROTATING_SPEED_OUT_OF_SCOPE_REVIEW": "Running speed is outside screened envelope and requires review.",
  "PHY.BEARING_TEMPERATURE_CRITICAL": "Bearing temperature is in critical zone.",
  "PHY.BEARING_TEMPERATURE_HIGH": "Bearing temperature is above recommended warning range.",
  "PHY.LUBE_OIL_TEMPERATURE_HIGH": "Lube-oil supply temperature is above warning threshold.",
  "PHY.LUBE_OIL_TEMPERATURE_CRITICAL": "Lube-oil supply temperature is in critical region.",
  "PHY.ROTATING_AXIAL_DISPLACEMENT_HIGH": "Axial displacement exceeds warning limit for machine class.",
  "PHY.ROTATING_AXIAL_DISPLACEMENT_CRITICAL": "Axial displacement exceeds critical limit for machine class.",
  "PHY.ROTATING_COUPLING_MISALIGNMENT_HIGH": "Coupling misalignment exceeds warning threshold.",
  "PHY.ROTATING_COUPLING_MISALIGNMENT_CRITICAL": "Coupling misalignment exceeds critical threshold.",
  "PHY.ROTATING_SURGE_RISK": "Compressor surge tendency is elevated from pressure ratio/events.",
  "PHY.ROTATING_SURGE_CRITICAL": "Compressor surge risk is critical from repeated events and high ratio.",
  "PHY.PUMP_NPSH_MARGIN_LOW": "NPSH margin is low and cavitation risk is increasing.",
  "PHY.PUMP_CAVITATION_RISK": "NPSH margin is negative, indicating likely cavitation risk.",
  "STD.API670_PROTECTION_GAP": "API 670 monitoring/protection coverage is below recommended level.",
  "STD.API670_PROTECTION_UNACCEPTABLE": "API 670 coverage is critically low for safe operation.",
  "STD.API670_TRIP_TEST_OVERDUE": "Trip test frequency is below required annual expectation.",
  "STD.API670_BYPASS_ACTIVE": "Protection bypass is active and train must be risk-reviewed immediately.",
  "LOG.DRIVER_MACHINE_MISMATCH": "Selected driver type is inconsistent with the machine topology.",
  "LOG.ROTATING_PRESSURE_RATIO_INCONSISTENT": "Pressure ratio input is inconsistent and should be reviewed.",
  "PHY.STEAM_PHASE_CHANGE_RISK": "Steam phase/wetness risk indicates erosion potential.",
  "PHY.ARC_FLASH_ENERGY_CRITICAL": "Arc-flash incident energy is at critical safety level.",
  "PHY.BREAKER_INTERRUPT_RATING_EXCEEDED": "Fault current exceeds breaker interrupt rating.",
  "PHY.ELECTRICAL_VOLTAGE_DROP_HIGH": "Voltage drop exceeds allowable limit.",
  "PHY.ELECTRICAL_THD_HIGH": "Voltage harmonic distortion exceeds limit.",
  "STD.SIL_TARGET_NOT_MET": "Calculated PFDavg does not meet SIL target.",
  "PHY.DRIFT_RATE_EXCEEDED": "Predicted drift is above tolerated range.",
  "PHY.CONTROL_VALVE_CAPACITY_INSUFFICIENT": "Required Cv exceeds rated Cv.",
  "PHY.STEEL_COLLAPSE_RISK_HIGH": "Steel demand/capacity indicates collapse risk.",
  "PHY.STEEL_CONNECTION_FAILURE": "Connection failure is flagged in inspection input.",
  "PHY.CIVIL_FLEXURE_OVERSTRESS": "Concrete member demand exceeds flexural capacity.",
  "PHY.CIVIL_SUBSTANTIAL_DAMAGE": "Substantial damage criteria are met.",
  "PHY.CIVIL_REBAR_CORROSION_INITIATED": "Carbonation depth reached cover depth.",
  "LOG.NO_CONSENSUS_AFTER_TIEBREAKER": "Consensus did not converge across verification agents.",
};

const FLAG_MESSAGES_KO: Record<string, string> = {
  "PHY.TEMPERATURE_LIMIT_EXCEEDED": "설계 온도가 관리 재질 한계를 초과했습니다.",
  "PHY.THICKNESS_BELOW_MINIMUM": "현재 벽두께가 최소 요구두께보다 낮습니다.",
  "PHY.REMAINING_LIFE_CRITICAL": "잔여수명이 임계 수준입니다.",
  "STD.HYDROTEST_CHLORIDE_LIMIT_EXCEEDED": "수압시험 염화물 농도가 재질 한계를 초과했습니다.",
  "PHY.CORROSION_RATE_UNREALISTIC": "계산된 부식률이 공학적 현실 범위를 벗어났습니다.",
  "PHY.VESSEL_THICKNESS_BELOW_REQUIRED": "용기 쉘 두께가 요구값보다 낮습니다.",
  "PHY.VESSEL_EXTERNAL_PRESSURE_RISK": "외압 사용률이 보수 기준을 초과했습니다.",
  "PHY.VESSEL_NOZZLE_REINFORCEMENT_RISK": "노즐 보강 스크리닝 결과 면적 부족이 의심됩니다.",
  "PHY.ROTATING_VIBRATION_CRITICAL": "선택된 기계 기준에서 진동이 임계치를 초과했습니다.",
  "PHY.ROTATING_VIBRATION_ABOVE_LIMIT": "기계/구동기/중요도 보정 경보한계를 초과했습니다.",
  "PHY.ROTATING_NOZZLE_LOAD_EXCEEDED": "가해진 노즐 하중이 허용 비율을 초과했습니다.",
  "PHY.ROTATING_NOZZLE_LOAD_NEAR_LIMIT": "노즐 하중이 보수 경고 한계 이상입니다.",
  "PHY.ROTATING_SPEED_CRITICAL_OUT_OF_SCOPE": "운전 속도가 스크리닝 운전 범위를 크게 벗어났습니다.",
  "STD.ROTATING_SPEED_OUT_OF_SCOPE_REVIEW": "운전 속도가 스크리닝 범위를 벗어나 검토가 필요합니다.",
  "PHY.BEARING_TEMPERATURE_CRITICAL": "베어링 온도가 임계 구간입니다.",
  "PHY.BEARING_TEMPERATURE_HIGH": "베어링 온도가 권장 경고 범위를 초과했습니다.",
  "PHY.LUBE_OIL_TEMPERATURE_HIGH": "윤활유 공급 온도가 경고 한계를 초과했습니다.",
  "PHY.LUBE_OIL_TEMPERATURE_CRITICAL": "윤활유 공급 온도가 임계 구간입니다.",
  "PHY.ROTATING_AXIAL_DISPLACEMENT_HIGH": "기계 등급 기준 축방향 변위가 경고 한계를 초과했습니다.",
  "PHY.ROTATING_AXIAL_DISPLACEMENT_CRITICAL": "기계 등급 기준 축방향 변위가 임계 한계를 초과했습니다.",
  "PHY.ROTATING_COUPLING_MISALIGNMENT_HIGH": "커플링 미스얼라인먼트가 경고 한계를 초과했습니다.",
  "PHY.ROTATING_COUPLING_MISALIGNMENT_CRITICAL": "커플링 미스얼라인먼트가 임계 한계를 초과했습니다.",
  "PHY.ROTATING_SURGE_RISK": "압력비/이벤트 기반 컴프레서 서지 경향이 높습니다.",
  "PHY.ROTATING_SURGE_CRITICAL": "반복 이벤트와 높은 압력비로 컴프레서 서지 위험이 임계 수준입니다.",
  "PHY.PUMP_NPSH_MARGIN_LOW": "NPSH 여유가 낮아 캐비테이션 위험이 증가하고 있습니다.",
  "PHY.PUMP_CAVITATION_RISK": "NPSH 여유가 음수로 캐비테이션 위험이 큽니다.",
  "STD.API670_PROTECTION_GAP": "API 670 감시/보호 커버리지가 권장 수준보다 낮습니다.",
  "STD.API670_PROTECTION_UNACCEPTABLE": "API 670 커버리지가 안전 운전을 위해 지나치게 낮습니다.",
  "STD.API670_TRIP_TEST_OVERDUE": "트립시험 빈도가 연간 요구 수준에 미달합니다.",
  "STD.API670_BYPASS_ACTIVE": "보호 기능 바이패스가 활성 상태이므로 즉시 위험 검토가 필요합니다.",
  "LOG.DRIVER_MACHINE_MISMATCH": "선택한 구동기 유형이 기계 토폴로지와 일치하지 않습니다.",
  "LOG.ROTATING_PRESSURE_RATIO_INCONSISTENT": "압력비 입력이 일관되지 않아 검토가 필요합니다.",
  "PHY.STEAM_PHASE_CHANGE_RISK": "스팀 상변화/습분 위험으로 침식 가능성이 있습니다.",
  "PHY.ARC_FLASH_ENERGY_CRITICAL": "아크플래시 입사 에너지가 임계 안전 수준입니다.",
  "PHY.BREAKER_INTERRUPT_RATING_EXCEEDED": "고장전류가 차단기 차단 정격을 초과했습니다.",
  "PHY.ELECTRICAL_VOLTAGE_DROP_HIGH": "전압강하가 허용 한계를 초과했습니다.",
  "PHY.ELECTRICAL_THD_HIGH": "전압 고조파 왜율이 한계를 초과했습니다.",
  "STD.SIL_TARGET_NOT_MET": "계산된 PFDavg가 SIL 목표를 충족하지 못했습니다.",
  "PHY.DRIFT_RATE_EXCEEDED": "예측 드리프트가 허용 범위를 초과했습니다.",
  "PHY.CONTROL_VALVE_CAPACITY_INSUFFICIENT": "요구 Cv가 정격 Cv를 초과합니다.",
  "PHY.STEEL_COLLAPSE_RISK_HIGH": "철골 수요/용량 비가 붕괴 위험 수준입니다.",
  "PHY.STEEL_CONNECTION_FAILURE": "입력 검사에서 접합부 파손이 표시되었습니다.",
  "PHY.CIVIL_FLEXURE_OVERSTRESS": "콘크리트 부재 수요가 휨 내력을 초과합니다.",
  "PHY.CIVIL_SUBSTANTIAL_DAMAGE": "중대 손상 기준에 해당합니다.",
  "PHY.CIVIL_REBAR_CORROSION_INITIATED": "탄산화 깊이가 피복두께에 도달했습니다.",
  "LOG.NO_CONSENSUS_AFTER_TIEBREAKER": "검증 에이전트 간 최종 합의에 도달하지 못했습니다.",
};

export function getFlagMessage(code: string, language: "en" | "ko" = "en"): string {
  if (language === "ko") {
    return FLAG_MESSAGES_KO[code] ?? FLAG_MESSAGES[code] ?? "검증 계층에서 발생한 코드 기반 경고/레드 플래그입니다.";
  }
  return FLAG_MESSAGES[code] ?? "Code-level warning/red flag from verification layer.";
}
