import type { GlossaryDiscipline } from "@/lib/glossary-types";
import type { StandardGlossaryEntry } from "@/lib/standards-types";

const LICENSED_TEXT_NOTE = "Full clause text is copyrighted; view through licensed publisher access.";

const PUBLISHER_URL = {
  ASME: "https://www.asme.org/codes-standards",
  API: "https://www.api.org/products-and-services/standards/digital-catalog",
  ISO: "https://www.iso.org/standard/78311.html",
  IEEE: "https://standards.ieee.org/standard/1584-2018.html",
  IEC: "https://webstore.iec.ch/searchform&q=61511",
  AISC: "https://www.aisc.org/standards/",
  ACI: "https://www.concrete.org/store/",
} as const;

export const STANDARD_GLOSSARY: StandardGlossaryEntry[] = [
  {
    code: "ASME VIII Div.1 UG-27",
    label: "Internal Pressure Shell Thickness",
    summary: "Defines minimum shell thickness for internal pressure cases and governing equation inputs/limits.",
    publisher: "ASME",
    officialUrl: PUBLISHER_URL.ASME,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["vessel"],
  },
  {
    code: "ASME VIII Div.1 UG-28",
    label: "External Pressure Buckling Check",
    summary: "Defines shell stability checks under external pressure with chart/table-based methodology.",
    publisher: "ASME",
    officialUrl: PUBLISHER_URL.ASME,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["vessel"],
  },
  {
    code: "ASME VIII Div.1 UG-37",
    label: "Nozzle / Opening Reinforcement",
    summary: "Defines reinforcement area requirements around openings/nozzles in pressure boundaries.",
    publisher: "ASME",
    officialUrl: PUBLISHER_URL.ASME,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["vessel"],
  },
  {
    code: "ASME B31.3 Para 304.1.2",
    label: "Piping Minimum Thickness",
    summary: "Defines pressure-design minimum wall-thickness equation and applicability for process piping.",
    publisher: "ASME",
    officialUrl: PUBLISHER_URL.ASME,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["piping"],
  },
  {
    code: "ASME B31.3 Table A-1",
    label: "Allowable Stress Table",
    summary: "Provides allowable stress values by material and temperature for design calculations.",
    publisher: "ASME",
    officialUrl: PUBLISHER_URL.ASME,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["piping", "common"],
  },
  {
    code: "API 570 Section 7",
    label: "Piping Integrity Assessment",
    summary: "Provides in-service piping assessment guidance for corrosion rate, remaining life, and intervals.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["piping"],
  },
  {
    code: "API 510",
    label: "Pressure Vessel In-Service Inspection",
    summary: "Defines pressure vessel in-service inspection planning, damage mechanisms, and repair governance.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["vessel"],
  },
  {
    code: "API 610",
    label: "Pump Mechanical Integrity",
    summary: "Defines centrifugal pump mechanical design and integrity requirements for process service.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 674",
    label: "Reciprocating Pump Integrity",
    summary: "Defines reciprocating positive-displacement pump mechanical and package integrity requirements.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 617",
    label: "Compressor Mechanical Integrity",
    summary: "Defines axial/centrifugal compressor mechanical integrity and package requirements.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 618",
    label: "Reciprocating Compressor Integrity",
    summary: "Defines reciprocating compressor mechanical design, package interfaces, and integrity constraints.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 619",
    label: "Rotary Positive-Displacement Compressor Integrity",
    summary: "Defines rotary PD compressor design and integrity requirements for process installations.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 672",
    label: "Packaged Integrally Geared Compressor Units",
    summary: "Defines packaged integrally geared compressor unit requirements and integration boundaries.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 611 / API 612",
    label: "Steam Turbine Drivers",
    summary: "Defines steam turbine driver requirements for rotating equipment and train-level integration.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 616",
    label: "Gas Turbine Drivers",
    summary: "Defines gas turbine driver requirements, interfaces, and integrity expectations for trains.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "API 670",
    label: "Machinery Protection Systems",
    summary: "Defines machinery protection system architecture, monitoring channels, and trip logic expectations.",
    publisher: "API",
    officialUrl: PUBLISHER_URL.API,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating", "instrumentation"],
  },
  {
    code: "ISO 20816-3",
    label: "Vibration Severity Guidance",
    summary: "Defines vibration severity evaluation zones and interpretation for industrial machines.",
    publisher: "ISO",
    officialUrl: PUBLISHER_URL.ISO,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["rotating"],
  },
  {
    code: "IEEE 1584",
    label: "Arc Flash Calculation",
    summary: "Defines empirical incident-energy methodology for arc-flash hazard calculations.",
    publisher: "IEEE",
    officialUrl: PUBLISHER_URL.IEEE,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["electrical"],
  },
  {
    code: "IEC 61511",
    label: "SIS Functional Safety",
    summary: "Defines SIS lifecycle requirements and SIL performance expectations for process industries.",
    publisher: "IEC",
    officialUrl: PUBLISHER_URL.IEC,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["instrumentation"],
  },
  {
    code: "AISC 360",
    label: "Steel Structural Design",
    summary: "Defines steel member strength, stability, and serviceability design requirements.",
    publisher: "AISC",
    officialUrl: PUBLISHER_URL.AISC,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["steel"],
  },
  {
    code: "ACI 318 / ACI 562",
    label: "Concrete Structural Integrity",
    summary: "Defines concrete design criteria and existing-structure assessment/rehabilitation requirements.",
    publisher: "ACI",
    officialUrl: PUBLISHER_URL.ACI,
    accessNote: LICENSED_TEXT_NOTE,
    disciplines: ["civil"],
  },
];

function indexMap(keys: string[]): Record<string, number> {
  return keys.reduce<Record<string, number>>((acc, key, index) => {
    acc[key.toUpperCase()] = index + 1;
    return acc;
  }, {});
}

export const PRIORITY_BY_DISCIPLINE: Record<GlossaryDiscipline, Record<string, number>> = {
  all: indexMap([
    "ASME B31.3 Para 304.1.2",
    "ASME B31.3 Table A-1",
    "API 570 Section 7",
    "ASME VIII Div.1 UG-27",
    "ASME VIII Div.1 UG-28",
    "ASME VIII Div.1 UG-37",
    "API 510",
    "API 610",
    "API 674",
    "API 617",
    "API 618",
    "API 619",
    "API 672",
    "API 611 / API 612",
    "API 616",
    "API 670",
    "ISO 20816-3",
    "IEEE 1584",
    "IEC 61511",
    "AISC 360",
    "ACI 318 / ACI 562",
  ]),
  common: indexMap([
    "ASME B31.3 Table A-1",
    "API 670",
  ]),
  piping: indexMap([
    "ASME B31.3 Para 304.1.2",
    "ASME B31.3 Table A-1",
    "API 570 Section 7",
  ]),
  vessel: indexMap([
    "ASME VIII Div.1 UG-27",
    "ASME VIII Div.1 UG-28",
    "ASME VIII Div.1 UG-37",
    "API 510",
  ]),
  rotating: indexMap([
    "API 610",
    "API 674",
    "API 617",
    "API 618",
    "API 619",
    "API 672",
    "API 611 / API 612",
    "API 616",
    "API 670",
    "ISO 20816-3",
  ]),
  electrical: indexMap([
    "IEEE 1584",
  ]),
  instrumentation: indexMap([
    "IEC 61511",
    "API 670",
  ]),
  steel: indexMap([
    "AISC 360",
  ]),
  civil: indexMap([
    "ACI 318 / ACI 562",
  ]),
};
